name: ONT-RefBasedAssembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=1.4.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - arrow-cpp=8.0.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - bcftools=1.16
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.39
  - bioawk=1.0
  - biopython=1.80
  - blinker=1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - chopper=0.5.0
  - clang=16.0.1
  - clang-16=16.0.1
  - click=8.1.3
  - coreutils=9.1
  - cryptography=39.0.0
  - cudatoolkit=11.1.1
  - cudnn=8.4.1.50
  - curl=7.87.0
  - deprecated=1.2.13
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpc-cpp=1.43.2
  - grpcio=1.43.0
  - gsl=2.7
  - h5py=3.7.0
  - harfbuzz=6.0.0
  - hdf5=1.12.2
  - htslib=1.16
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - intervaltree=3.0.2
  - jpeg=9e
  - k8=0.2.5
  - kaleido-core=0.2.1
  - keras=2.7.0
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang-cpp16=16.0.1
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgoogle-cloud=1.36.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm16=16.0.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.19.4
  - libsanitizer=12.2.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - longshot=0.4.5
  - lz4-c=1.9.3
  - mappy=2.24
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mathjax=2.7.7
  - medaka=1.7.2
  - minimap2=2.24
  - multidict=6.0.4
  - nanofilt=2.8.0
  - nanoget=1.18.1
  - nanomath=1.2.1
  - nanoplot=1.41.0
  - nccl=2.14.3.1
  - ncurses=6.3
  - nextflow=22.10.4
  - nspr=4.35
  - nss=3.82
  - numpy=1.19.5
  - oauthlib=3.2.2
  - ont-fast5-api=4.1.1
  - openjdk=17.0.3
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - orc=1.7.3
  - packaging=23.0
  - pandas=1.4.4
  - parasail-python=1.3.3
  - parquet-cpp=1.5.1
  - pcre2=10.40
  - perl=5.32.1
  - pip=22.3.1
  - pixman=0.40.0
  - plotly=5.11.0
  - porechop=0.2.4
  - primerclip=0.3.8
  - progressbar33=2.4
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - pyarrow=8.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pysam=0.20.0
  - pysocks=1.7.1
  - pyspoa=0.0.3
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-edlib=1.3.9
  - python-flatbuffers=2.0
  - python-kaleido=0.2.1
  - python_abi=3.8
  - pytz=2022.7.1
  - pyu2f=0.1.5
  - pyvcf3=1.0.3
  - re2=2022.02.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - s2n=1.0.10
  - samtools=1.16.1
  - scipy=1.9.1
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - sqlite=3.40.0
  - sysroot_linux-64=2.12
  - tar=1.34
  - tenacity=8.1.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.7.1
  - tensorflow-base=2.7.1
  - tensorflow-estimator=2.7.1
  - termcolor=2.2.0
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - vcftools=0.1.16
  - werkzeug=2.2.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yarl=1.8.2
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
